verifyEmail & verifyUser API
field-seating/field-seating-api pull request #13
Opened 2022-04-14 13:14 UTC by RonnyChiang

新增兩個API 及兩個service
API:
GET/api/users/verify-email 寄發驗證信
PATCH/api/api/verify-email/:token 驗證使用者

service:
sendVerifyEmail
verifyUser

helpers: 
send-email 使用第三方套件[sendinblue](https://developers.sendinblue.com/recipes)
retry 重複測試第三方錯誤

2022-04-14 13:19 UTC, WendellLiu commented
Task linked: [CU-2k0hn44 verifyEmail & verifyUser API](https://app.clickup.com/t/2k0hn44)

2022-04-14 14:44 UTC, WendellLiu commented on src/config/config.js
> +    baseUrl: 'http://localhost:3000',
參考https://app.clickup.com/25699357/v/dc/rg90x-365/rg90x-465
並且production 也需要

另外倒是終於發現了需要區分staging 的用途，我會開張票。目前先把prd 視為stg 沒問題

2022-04-14 16:11 UTC, WendellLiu requested changes
東西有點多，所以千萬千萬記得不要rebase ，不然我下次review 會發瘋 XD
而且可能就會漏回來撿逃這次點出的問題

2022-04-14 16:11 UTC, WendellLiu commented on src/services/email-service.test.js
> +    });
一樣，都不應該回傳的，就算你真的回傳了，也不是測試的重點
我想這邊要確認的應該會是sendEmail 有沒有如期被呼叫（你上的有寫的）、sendEmail 有沒有獲得對應的參數，另用toBeCalledWith 相關的assertion 去寫

2022-04-14 16:11 UTC, WendellLiu commented on src/services/email-service.test.js
> +      const newUser = await userService.signUp('user1', email, 'password1');
不理解你這邊需要呼叫到userService 的意義在哪？你的設計上sendVerifyEmail 完全沒有跟真實資料互動吧

2022-04-14 16:11 UTC, WendellLiu commented on src/services/user-service.js
> +        throw new GeneralError();
這樣的話使用者會看到什麼？顯然不是很對

2022-04-14 16:11 UTC, WendellLiu commented on src/services/user-service.test.js
> +        status: 'verified',
no magic string

2022-04-14 16:11 UTC, WendellLiu commented on src/services/user-service.test.js
> +      const sendVerifyEmail = await emailServices.sendVerifyEmail(newUser);
與email service 測試一樣
依照你的設計，userservice.verfiyuser 與sendVerfiyEmail 完全無關
你這裡顯然也只是憑藉著你傳出的多餘回傳值來測試，並不是很合理

你的測試標的是對的，要測試當正確與不正確token 進去時會發生什麼事，如何應對
這邊是沒問題的
但有問題的是，「產出token 」這件事並不是depend on emailService.sendVerifyEmail ，想想你真的應該要使用的工具是什麼，甚至是不是該工具夠簡單不需要mock 了

2022-04-14 16:11 UTC, WendellLiu commented on src/services/user-service.test.js
> +        await userService.verifyUser(wrongToken.token);
看看你真的用到的東西，再看看你產出的變數，問題應該蠻明顯了

2022-04-15 03:29 UTC, WendellLiu commented on src/constants/jwt-constant.js
> +const verifyTokenLife = '5m';
config

2022-04-17 11:45 UTC, WendellLiu requested changes

2022-04-17 11:45 UTC, WendellLiu commented on src/config/config.js
> +  email: process.env.EMAIL,
1. naming. proposal: emailSender
2. 是不是不需要是環境變數？

2022-04-17 11:45 UTC, WendellLiu commented on src/utils/func/retry.js
> +      console.log(count);
remove the log

2022-04-17 11:45 UTC, WendellLiu commented on src/services/email-service.js
> +      emailList: [
naming; proposal: receiverList

2022-04-17 11:45 UTC, WendellLiu commented on src/services/email-service.js
> +      this.logger.info('sent email', {});
`this.logger.info('sent email', emailInfo);` ?

2022-04-17 11:45 UTC, WendellLiu commented on src/services/helpers/send-email.js
> +async function sendEmail(templateName, meta, data) {
少了一些參數檢查的處理

2022-04-17 11:45 UTC, WendellLiu commented on src/services/user-service.test.js
> +const UserModel = require('../models/user/index');
index is unnecessary

2022-04-18 08:21 UTC, RonnyChiang commented on src/config/config.js
> +  email: process.env.EMAIL,
移除環境變數

2022-04-18 08:21 UTC, RonnyChiang commented on src/services/email-service.js
> +      emailList: [
fixed

2022-04-18 08:21 UTC, RonnyChiang commented on src/services/helpers/send-email.js
> +async function sendEmail(templateName, meta, data) {
add

2022-04-18 08:22 UTC, RonnyChiang commented on src/services/user-service.test.js
> +const UserModel = require('../models/user/index');
fixed

2022-04-18 08:31 UTC, WendellLiu requested changes

2022-04-18 08:31 UTC, WendellLiu commented on src/services/helpers/send-email.js
> +    throw new PrivateError(sendEmailErrorMap['noEmailAddressError']);
1. naming: isInvalidEmail (or isValidEmail, 看你想要的方向)
2. 變數為何是event?
3. 為何是every ?

2022-04-18 08:31 UTC, WendellLiu commented on src/services/helpers/send-email.js
> +    sender: { email: 'ronnychiang1164@gmail.com', name: '球場坐座Team' },
不是很能理解為什麼你寫死第一個想到的是你的信箱，現在是不急於改，不過我覺得這個想法是有點奇怪了點

2022-04-18 08:47 UTC, RonnyChiang commented on src/services/helpers/send-email.js
> +    throw new PrivateError(sendEmailErrorMap['noEmailAddressError']);
已修正

2022-04-18 08:48 UTC, RonnyChiang commented on src/services/helpers/send-email.js
> +    sender: { email: 'ronnychiang1164@gmail.com', name: '球場坐座Team' },
先改成field-seating@gmail.com

2022-04-18 08:48 UTC, RonnyChiang commented on src/services/helpers/send-email.js
> +    sender: { email: 'ronnychiang1164@gmail.com', name: '球場坐座Team' },
先改成field-seating@gmail.com

2022-04-18 09:10 UTC, WendellLiu approved these changes

2022-04-18 11:27 UTC, merged