feat: add unique username
field-seating/field-seating-api pull request #21
Opened 2022-04-22 07:25 UTC by RonnyChiang

修正username限制，獨一且小於20字。

2022-04-22 07:30 UTC, WendellLiu commented
Task linked: [CU-2tydgq8 user name update](https://app.clickup.com/t/2tydgq8)

2022-04-22 07:52 UTC, WendellLiu commented on prisma/schema.prisma
> +  name      String   @unique @db.VarChar(40)
不是說就給多一點嗎ＸＤ

觀念是空間可以預留，一些商業邏輯可以先做在application 就好，以varchar case 為例，空間如果未來要增大，migrate 就會很麻煩

我覺得至少可以開到60-80

2022-04-22 07:52 UTC, WendellLiu commented on src/errors/sign-up-error.js
> +    message: '名稱超過資料庫限制',
應該是不必暴露資料庫任何資訊
message 可以跟上面的一樣，但我們用code 區分

2022-04-22 07:52 UTC, WendellLiu commented on src/errors/sign-up-error.js
> +  tooLongName: {
maximumExceededName 如何？
下方亦同

2022-04-22 07:52 UTC, WendellLiu commented on src/services/user-service.js
> +      if (err.meta.target === 'Users_email_key') {
如果是我搞錯可以說。
但我看起來 err.meta.target 只是在指出error 是發生在哪個欄位
為什麼err.meta.target === 'Users_email_key' 就能代表是email duplication error ?

2022-04-22 07:52 UTC, WendellLiu commented on src/services/user-service.js
> +      if (err.meta.target === 'Users_name_key') {
ditto

2022-04-22 07:52 UTC, WendellLiu commented on src/services/user-service.js
> +      if (err.code === 'P2000') {
為什麼這個一定是for name?

2022-04-22 07:52 UTC, WendellLiu commented on src/services/user-service.test.js
> +  });
接續上面的comment
如果我的想法沒錯，你的case 加上以下「當email 超過255 時，會出現非general error 以外的error」會失敗，理論上應該會回傳GeneralError(signUpErrorMap['duplicateEmail']); ？

2022-04-22 07:53 UTC, WendellLiu requested changes
1. varchar limit
2. catch 錯的邏輯有問題，不能將「剛好」視為「必然」

2022-04-27 04:03 UTC, RonnyChiang commented on prisma/schema.prisma
> +  name      String   @unique @db.VarChar(40)
update to 80

2022-04-27 04:03 UTC, RonnyChiang commented on src/errors/sign-up-error.js
> +  tooLongName: {
ok

2022-04-27 04:04 UTC, RonnyChiang commented on src/services/user-service.js
> +      if (err.meta.target === 'Users_email_key') {
外面加上code判斷 P2002

2022-04-27 04:04 UTC, RonnyChiang commented on src/services/user-service.js
> +      if (err.code === 'P2000') {
裡面加上target 判斷

2022-04-27 04:05 UTC, RonnyChiang commented on src/services/user-service.test.js
> +  });
修正後應該就沒這問題了

2022-04-27 04:14 UTC, WendellLiu requested changes

2022-04-27 04:14 UTC, WendellLiu commented on prisma/migrations/20220427032813_fix_username_length/migration.sql
> +ALTER TABLE `Users` MODIFY `name` VARCHAR(80) NOT NULL;
與另一個PR 一樣，縮減為一個migration file

2022-04-27 04:14 UTC, WendellLiu commented on src/errors/sign-up-error.js
> +    message: '名稱不可超過20字',
應該就不是20 字了？

2022-04-27 04:14 UTC, WendellLiu commented on src/services/user-service.js
> +        throw err;
不必要

2022-04-27 04:14 UTC, WendellLiu commented on src/services/user-service.js
> +        throw err;
不必要

2022-04-27 04:14 UTC, WendellLiu commented on src/services/user-service.js
> +        }
不要兩層條件（包括上面）

2022-04-30 11:34 UTC, WendellLiu approved these changes

2022-04-30 11:47 UTC, merged