Fix user verify
field-seating/field-seating-api pull request #25
Opened 2022-04-27 03:04 UTC by RonnyChiang

修正verify email ：改採uuid 存入uuid及產生時間於資料庫中供比對．
修正resend email : 增加時間判斷

2022-04-27 03:07 UTC, WendellLiu commented
Task linked: [CU-2tydugp Differentiate Email Verification Token and API token to avoid user using API token to verify email](https://app.clickup.com/t/2tydugp)

2022-04-27 04:09 UTC, WendellLiu requested changes

2022-04-27 04:09 UTC, WendellLiu commented on src/services/user-service.test.js
> +          date: new Date(),
和上面一樣，這裡根本沒有mock 的必要性
1. 請不要在沒必要mock 的地方mock ，增加不可預測性以及增加測試時間
2. 而這邊也與上面一樣，事實上你最後的assertion 沒有去驗證資料的改變是很奇怪的。這個service 會造成什麼side effect ？這應該才是測試重點 。
3. 事實上 userService.verifyEmail 根本不需要回傳吧？我一樣認為這個「回傳」本身不是問題，但我建議你在你還沒弄清楚測試重點前，在實作時能不回傳就不要回傳，否則你會一直出現這種不在點上的測試

2022-04-27 04:09 UTC, WendellLiu commented on src/services/user-service.test.js
> +    });
為什麼沒有任何資料進去就能做verifyEmail ？這個測試在測試的是當users 為空的錯誤處理還是token 錯誤的錯誤處理？

2022-04-27 04:09 UTC, WendellLiu commented on src/services/user-service.js
> +  async refreshToken(id) {
refreshToken 是一個常見的專用名詞，改個命名，`flushToken` ? 相對應的地方也一併改

2022-04-29 09:35 UTC, WendellLiu commented on .vscode/settings.json
> +}
確定一下，這有需要跟版嗎？因為我是用不到，但放著也無妨，如果真的有需要

2022-04-29 09:35 UTC, WendellLiu commented on prisma/migrations/20220427052354_init/migration.sql
squash 後的檔名還是可以有語意一點吧我想

2022-04-29 09:35 UTC, WendellLiu commented on src/services/user-service.test.js
> +      const mockDate = addMilliseconds(new Date(), verificationTokenLife);
為什麼是milliseconds ?

2022-04-29 11:55 UTC, RonnyChiang commented on prisma/migrations/20220427052354_init/migration.sql
fixed

2022-04-29 11:55 UTC, RonnyChiang commented on .vscode/settings.json
> +}
已刪除

2022-04-29 16:27 UTC, WendellLiu commented on src/services/user-service.test.js
>    });
```js
  describe('with expired token', () => {
    it('should return error: invalidToken', async () => {
      const email = 'example@example.com';
      const newUser = await userService.signUp('user1', email, 'password1');

      // make a fake day which expired token life
      const mockDate = addSeconds(new Date(), verificationTokenLife);
      jest.useFakeTimers();
      jest.setSystemTime(mockDate);

      try {
        await userService.verifyEmail(newUser.verificationToken);
      } catch (e) {
        // make sure get the right err code
        expect(e.code).toBe(verifyErrorMap.invalidToken.code);
      }

      // clean
      jest.useRealTimers();
    });
  });
```

2022-04-29 16:33 UTC, RonnyChiang commented on src/services/user-service.test.js
>    });
good

2022-04-29 16:56 UTC, WendellLiu reviewed
剩下幾個小東西以及我跟你討論的測試問題，你說得蠻對的，我自己也有發現但一直沒去面對它，我稍微試試看，如果可以就在你這邊開始讓我們改個寫法

2022-04-29 16:56 UTC, WendellLiu commented on src/services/user-service.test.js
> +        console.log(test);
remove

2022-04-29 16:56 UTC, WendellLiu commented on src/services/user-service.test.js
> +        console.log(e);
remove

2022-04-29 16:56 UTC, WendellLiu commented on src/services/user-service.test.js
> +      const mockDate = addSeconds(new Date(), verificationTokenLife);
疑問是：本來的測試情境有錯，但還是過了，在你沒有換實作、換斷言的情況下，你改了測試情境也過了，那應該表示有什麼事情有問題。簡單的說你現在的「過」暫不能代表什麼

2022-04-29 16:56 UTC, WendellLiu commented on src/services/user-service.test.js
> +      const verifyUser = await userService.flushToken(newUser.id);
小事，這應該是個token?

2022-04-29 17:16 UTC, WendellLiu commented on src/services/user-service.test.js
> +      const mockDate = addSeconds(new Date(), verificationTokenLife);
後來想說直接找個更方便的assertion tool 用在這個情境，不過發現原來nodejs 原生就有，所以以後錯誤處理的assertion  就用這個模式吧

先引用
```js
const assert = require('assert/strict');
```

assertion 的部分改成：
```js
      assert.rejects(
        async () => {
          await userService.verifyEmail(newUser.verificationToken);
        },
        {
          code: verifyErrorMap.invalidToken.code,
        }
      );

```

也有https://nodejs.org/api/assert.html#assertthrowsfn-error-message
如果是同步函數可以改成用 `assert.throw`

2022-04-30 05:03 UTC, RonnyChiang commented on src/services/user-service.test.js
> +        console.log(test);
fixed

2022-04-30 05:04 UTC, RonnyChiang commented on src/services/user-service.test.js
> +        console.log(e);
fixed

2022-04-30 05:04 UTC, RonnyChiang commented on src/services/user-service.test.js
> +      const mockDate = addSeconds(new Date(), verificationTokenLife);
ok

2022-04-30 05:04 UTC, RonnyChiang commented on src/services/user-service.test.js
> +      const verifyUser = await userService.flushToken(newUser.id);
fixed

2022-04-30 12:41 UTC, WendellLiu approved these changes

2022-04-30 15:46 UTC, merged