[CU-2xw9f2p] Post photos api
field-seating/field-seating-api pull request #32
Opened 2022-05-17 09:44 UTC by RonnyChiang

完成上傳照片功能，新增一項測試．
使用三個utils

2022-05-17 09:44 UTC, WendellLiu commented
Task linked: [CU-2xw9f2p postPhoto API](https://app.clickup.com/t/2xw9f2p)

2022-05-17 10:55 UTC, WendellLiu requested changes

2022-05-17 10:55 UTC, WendellLiu commented on src/utils/upload-image/resize.js
> +        .jpeg({ quality: 90 })
所以format 不是jpeg 這行也行嗎？

2022-05-17 10:55 UTC, WendellLiu commented on src/utils/upload-image/resize.js
> +          throw new PrivateError(err);
為什麼需要在這邊做這件事？尤其沒有多做處理的情況
1. 這個util 有有別於其他util 之處？
2. 不能在使用的地方做？

2022-05-17 10:55 UTC, WendellLiu commented on prisma/schema.prisma
> +  previewFeatures = ["interactiveTransactions"]
這兩行的修改是差別是？

2022-05-17 10:55 UTC, WendellLiu commented on src/constants/resize-constant.js
> +    { size: 640, name: 'thumb_' },
namePrefix 好一點

2022-05-17 10:55 UTC, WendellLiu commented on src/config/config.js
> +  domain: process.env.DOMAIN,
看起來不需要都從環境變數來，回想一下分不同層的意義

2022-05-17 10:55 UTC, WendellLiu commented on src/errors/post-photo-error.js
> +  toLargeFile: {
tooLargeFile

2022-05-17 10:55 UTC, WendellLiu commented on src/middleware/multer.js
> +    }
看起來可以early return ，參考之前的例子

2022-05-17 10:55 UTC, WendellLiu commented on src/middleware/multer.js
> +  uploadImages,
你這個檔案充滿了upload Image 的context ，例如 `multerFilter` 的錯誤處理。另外也不需要曝露出multer 的資訊。
或許整個module 命名成 `middleware/upload-images` 即可

2022-05-17 10:55 UTC, WendellLiu commented on src/models/space.js
> +        zone: {
為什麼需要拿出zone ?

2022-05-17 10:55 UTC, WendellLiu commented on src/routes/index.js
> +router.use('/api/photos', authenticated, photo);
我覺得可以不需要斷言這邊會用到authenticated ，例如我們現在不確定 GET /api/photos 會是public or private

2022-05-17 10:55 UTC, WendellLiu commented on src/services/photo-service.js
> +      if (err.code === 'P2002' && err.meta.target === 'Users_name_key') {
感覺你應該沒錯，不過稍微解釋一下為什麼是 `Users_name_key` ?

2022-05-17 10:55 UTC, WendellLiu commented on .env.test
> +SPACES_SECRET=
這看起來用不到？

2022-05-17 10:55 UTC, WendellLiu commented on .env.test
> +SPACES_SECRET=
另外這個檔案怎麼多出來了？

2022-05-17 10:55 UTC, WendellLiu commented on src/controllers/photo-controller.js
> +  postPhotos: async (req, res, next) => {
我以為我們聊過了，不要有這麼大、複雜的controller

2022-05-17 10:55 UTC, WendellLiu commented on src/controllers/photo-controller.js
> +  postPhotos: async (req, res, next) => {
方向是我想大部分東西應該都在photoService.postPhotos，如果你想單元化目前 `postPhotos` 的行為，可以考慮改為`postPhoto` 然後將大部分內容放在 `postPhotos`

以上都只是建議，要解決的問題是service 與controller 的分權

2022-05-17 10:55 UTC, WendellLiu commented on src/config/config.js
> +  domain: process.env.DOMAIN,
另外domain 顯然太implicit ，這邊可以是 asset domain

2022-05-17 10:55 UTC, WendellLiu commented on src/models/photo.js
> +        date: dateTime,
為什麼需要時間？

2022-05-17 10:55 UTC, WendellLiu commented on src/services/photo-service.test.js
> +      expect(newPhoto).toMatchObject(expectedResult);
看完這個測試就會想到上面controller 那邊說的，我想最大的問題是，你的service 根本沒包含什麼邏輯，因此都在controller 了，並且也沒有controller 的測試。

考量到測試金字塔，我們希望的目標是以測試service 為重、其次是model, helper, utils 等基礎工具，最後才是controller 
但要做到這樣，相應的是邏輯的拆分

以這個測試為例，很明顯根本看不出想測試什麼，看起來就是在測試那個model ，甚至是prisma API 的測試？

呼應上面說的，建議可以把目前的service 獨立出來，乾脆就不測試了，但新增一個真正有意義的service ，然後對他寫測試

2022-05-17 10:55 UTC, WendellLiu commented on src/utils/upload-image/random-hash-name.js
> +  const hashFilename = await hashPassword(randomFilename, 2);
除了naming ，從「介面」來看一個很大的問題是，這裡並不需要salt，僅需要一個能保證唯一的hash alogrithm 即可（也因此就不會是password ）

2022-05-19 08:57 UTC, WendellLiu commented on src/utils/upload-image/resize.js
> +  const resizeFiles = [];
剛看到，這樣也一樣，改一下

2022-05-19 08:57 UTC, WendellLiu commented on src/utils/upload-image/resize.js
> +  const resizeFiles = [];
剛看到，這樣也一樣，改一下

2022-05-20 06:22 UTC, RonnyChiang commented on src/utils/upload-image/resize.js
> +  const resizeFiles = [];
fixed

2022-05-20 06:22 UTC, RonnyChiang commented on src/utils/upload-image/resize.js
> +  const resizeFiles = [];
same issue

2022-05-20 06:22 UTC, RonnyChiang commented on src/services/photo-service.js
> +    let uploadInfo = [];
fixed

2022-05-20 06:22 UTC, RonnyChiang commented on src/services/photo-service.js
> +          resizeFiles.map(async (resizeFile) => {
fixed

2022-05-20 06:22 UTC, RonnyChiang commented on src/services/photo-service.js
> +  async postPhotos(spaceId, files, requestId, userId, date) {
fixed

2022-05-20 06:22 UTC, RonnyChiang commented on src/services/photo-service.test.js
> +      expect(newPhoto).toMatchObject(expectedResult);
fixed

2022-05-20 06:23 UTC, RonnyChiang commented on src/controllers/photo-controller.js
> +  postPhotos: async (req, res, next) => {
fixed

2022-05-20 06:23 UTC, RonnyChiang commented on .env.test
> +SPACES_SECRET=
deleted

2022-05-20 06:23 UTC, RonnyChiang commented on src/services/photo-service.js
> +      if (err.code === 'P2002' && err.meta.target === 'Users_name_key') {
fixed to  === Photos_path_key

2022-05-20 06:24 UTC, RonnyChiang commented on src/routes/index.js
> +router.use('/api/photos', authenticated, photo);
fixed for only postPhotos

2022-05-20 06:24 UTC, RonnyChiang commented on src/models/space.js
> +        zone: {
deleted

2022-05-20 06:24 UTC, RonnyChiang commented on src/middleware/multer.js
> +  uploadImages,
fixed

2022-05-20 06:24 UTC, RonnyChiang commented on src/middleware/multer.js
> +    }
fixed

2022-05-20 06:24 UTC, RonnyChiang commented on src/errors/post-photo-error.js
> +  toLargeFile: {
fixed

2022-05-20 06:24 UTC, RonnyChiang commented on src/config/config.js
> +  domain: process.env.DOMAIN,
fixed

2022-05-20 06:25 UTC, RonnyChiang commented on src/constants/resize-constant.js
> +    { size: 640, name: 'thumb_' },
fixed

2022-05-20 06:26 UTC, RonnyChiang commented on src/utils/upload-image/resize.js
> +          throw new PrivateError(err);
deleted  依靠外層catch

2022-05-20 06:27 UTC, RonnyChiang commented on src/utils/upload-image/resize.js
> +        .jpeg({ quality: 90 })
fixed toFormat(format, { quality: xx})

2022-05-20 06:27 UTC, RonnyChiang commented on src/utils/upload-image/random-hash-name.js
> +  const hashFilename = await hashPassword(randomFilename, 2);
fix new utils

2022-05-20 08:49 UTC, WendellLiu commented
add secret on PR, https://github.com/field-seating/devops-ansible/pull/3

2022-05-20 08:52 UTC, WendellLiu approved these changes
LGTM

2022-05-20 08:52 UTC, WendellLiu commented on src/middleware/upload-images.js
> +    // others err we don't know
不相關的事：other errs we don't know

2022-05-20 08:52 UTC, WendellLiu commented on src/services/photo-service.test.js
> +      const spaceId = newSpace.id + 1;
算是有點大費周章生出這個id XDD

2022-05-20 08:52 UTC, WendellLiu commented on src/services/photo-service.test.js
> +  describe('with not existed space', () => {
小事
with absent space / with unexisting space / with non-existing space

2022-05-22 05:06 UTC, merged