[CU-2yryj4d] Data build
field-seating/field-seating-api pull request #34
Opened 2022-05-25 11:40 UTC by RonnyChiang

set seeding

2022-05-25 11:40 UTC, WendellLiu commented
Task linked: [CU-2yryj4d set seeding](https://app.clickup.com/t/2yryj4d)

2022-05-25 11:51 UTC, RonnyChiang commented on seeders/data.json
> +{
data.json 建立球場區(zone)域資料

2022-05-26 12:38 UTC, RonnyChiang commented on seeders/spaces/space-generator.js
> +const fs = require('fs');
generator取得區域相關資訊（排列數） 生成space資訊（input csv）
再將該csv於google sheet 載入後編輯spaceType
編輯完後匯出csv供seed.js使用

2022-05-27 03:29 UTC, WendellLiu requested changes

2022-05-27 03:29 UTC, WendellLiu commented on package.json
> +    "spacesCsv-gene": "node seeders/spaces/space-generator.js"
generate

2022-05-27 03:29 UTC, WendellLiu commented on prisma/seed.js
> +  const fileContent = await fs.promises.readFile('./seeders/spaces/westAB.csv'); // data of space
這個PR 的目標是：
> 進去之後，再來只要丟入相對應的Raw Data 就能跑

因此你這邊hardcode 讀一個檔案，顯然是不符目標的

2022-05-27 03:29 UTC, WendellLiu commented on prisma/seed.js
> +  await fieldModel.createField(data.field);
ditto; 如果你假設一個file 是代表一個球場，那hardcode 讀一個檔案是不符合目標的，又如果你是假設一個檔案就是所有的field, level, orientation, zone 那data.field 的型別不符合你的預期

2022-05-27 03:29 UTC, WendellLiu commented on prisma/seed.js
> +    data.orientations.map(async (orientation) => {
orientationName

2022-05-27 03:29 UTC, WendellLiu commented on prisma/seed.js
> +    data.levels.map(async (level) => {
levelName

2022-05-27 03:29 UTC, WendellLiu commented on src/models/field.js
> +  async searchField(name) {
search 就不會是一個，建議是getFieldByName；其他亦同

2022-05-27 03:29 UTC, WendellLiu commented on prisma/seed.js
> +        const field = await fieldModel.searchField(zone.field);
有naming 問題，參照model 處的comment

2022-05-27 03:29 UTC, WendellLiu commented on prisma/seed.js
> +      const fieldId = await fieldMap.get(zone.field);
Map.get 不是非同步吧

2022-05-27 03:29 UTC, WendellLiu commented on prisma/seed.js
> +async function readCsv() {
如果你要讓這個函數專門讀某些檔案，那naming 清楚一點，如果這個naming 他我想他會是需要個參數

2022-05-27 03:29 UTC, WendellLiu commented on seeders/spaces/space-generator.js
> +    for (let r = zoneMap[z].row[0]; r < zoneMap[z].row[1] + 1; r++) {
不要沒必要的縮寫，zoneIndex, col, row

2022-05-27 03:29 UTC, WendellLiu commented on seeders/spaces/space-generator.js
> +    for (let r = zoneMap[z].row[0]; r < zoneMap[z].row[1] + 1; r++) {
zoneMap[z] 看起來是可以在第一層迴圈被定義的，並且也給他可讀性高的變數名稱

2022-05-27 03:29 UTC, WendellLiu commented on seeders/spaces/space-generator.js
> +      var data = [
const

2022-05-27 03:29 UTC, WendellLiu commented on src/services/photo-service.js
> +const SpaceModel = require('../models/space/index');
不需要index

2022-05-27 03:29 UTC, WendellLiu commented on src/services/photo-service.test.js
> +const SpaceModel = require('../models/space/index');
不需要index

2022-05-27 03:29 UTC, WendellLiu commented on src/models/space/index.js
> +          zone: {
有需要join zone？

2022-05-27 03:29 UTC, WendellLiu commented on src/models/space/index.js
> +      const createSpace = await prisma.spaces.create({
不要重複命名

2022-05-27 14:32 UTC, RonnyChiang commented on prisma/seed.js
> +  const fileContent = await fs.promises.readFile('./seeders/spaces/westAB.csv'); // data of space
已修正 讀取資料夾

2022-05-27 14:33 UTC, RonnyChiang commented on prisma/seed.js
> +  await fieldModel.createField(data.field);
決定將個球場資訊放入同一個json 並修正

2022-05-27 14:33 UTC, RonnyChiang commented on prisma/seed.js
> +    data.orientations.map(async (orientation) => {
fixed

2022-05-27 14:33 UTC, RonnyChiang commented on src/models/field.js
> +  async searchField(name) {
fixed

2022-05-27 14:33 UTC, RonnyChiang commented on prisma/seed.js
> +        const field = await fieldModel.searchField(zone.field);
fixed

2022-05-27 14:34 UTC, RonnyChiang commented on prisma/seed.js
> +async function readCsv() {
rename to getSpacesData

2022-05-27 14:34 UTC, RonnyChiang commented on seeders/spaces/space-generator.js
> +    for (let r = zoneMap[z].row[0]; r < zoneMap[z].row[1] + 1; r++) {
fixed

2022-05-27 14:34 UTC, RonnyChiang commented on seeders/spaces/space-generator.js
> +      var data = [
fixed

2022-05-27 14:34 UTC, RonnyChiang commented on src/services/photo-service.js
> +const SpaceModel = require('../models/space/index');
fixed

2022-05-27 14:34 UTC, RonnyChiang commented on src/services/photo-service.test.js
> +const SpaceModel = require('../models/space/index');
fixed

2022-05-27 14:34 UTC, RonnyChiang commented on src/models/space/index.js
> +      const createSpace = await prisma.spaces.create({
fixed

2022-05-28 13:08 UTC, WendellLiu reviewed
一個地方

2022-05-28 13:08 UTC, WendellLiu commented on prisma/seed.js
> +    throw new err();
為什麼是err() ?

2022-05-28 15:54 UTC, RonnyChiang commented on prisma/seed.js
> +    throw new err();
fixed 拿掉 try catch 不做處理

2022-05-31 09:38 UTC, WendellLiu approved these changes

2022-05-31 10:54 UTC, merged