[CU-2yd7vc1] Get fields info
field-seating/field-seating-api pull request #37
Opened 2022-06-08 08:01 UTC by RonnyChiang

API: 

1. GET /api/fields
2. GET /api/fields/:id/levels
3. GET /api/fields/:id/orientations
4. GET /api/fields/:id/zones?orientation=1&level=2
5. GET /api/zones/:id/spaces

test: 
zone.service.test

2022-06-08 08:02 UTC, WendellLiu commented
Task linked: [CU-2yd7vc1 Get fields info](https://app.clickup.com/t/2yd7vc1)

2022-06-08 09:39 UTC, RonnyChiang commented on src/models/space/index.js
> +          positionRowNumber,
positionNum is not nullable

2022-06-08 09:41 UTC, RonnyChiang commented on src/models/space/index.js
> +    }
未輸入任何spaceType情況

2022-06-08 09:56 UTC, WendellLiu commented on src/models/space/index.js
> +  async getZoneSpaces(zoneId, spaceType) {
1. 直接兩個method 去處理有或沒有spaceType，直接少那些判斷
2. spaceTypes always，精神一樣，減少判斷，直接鎖定行別為Array of spaceType
3. naming: getSpacesByZoneAndSpaceTypes, getSpacesByZone

2022-06-08 10:10 UTC, WendellLiu requested changes

2022-06-08 10:10 UTC, WendellLiu commented on src/models/zone.js
> +  async getFieldZones(fieldId, orientationId, levelId) {
getZonesByField
跟上面有說的一樣，不過我發現你主要是蠻不同步的。

2022-06-08 10:10 UTC, WendellLiu commented on src/services/field-service.js
> +    if (!levelList[0]) throw new GeneralError(getListErrorMap['fieldNotFound']);
我覺得蠻怪的，事實上這邊如果回來的陣列是空的，也不等同於field not found 對吧！？
看你是要真的去確認field not found 這件事，或是改一下error

2022-06-08 10:10 UTC, WendellLiu commented on src/services/zone-service.js
> +    if (!spaces[0]) throw new GeneralError(getListErrorMap['zoneNotFound']);
ditto; 同步一下邏輯與錯誤種類

2022-06-08 10:10 UTC, WendellLiu commented on src/services/zone-service.test.js
> +      const spaceList = await zoneService.getZoneSpaces(newZone.id, 'seat');
space type 何不從constant 來？

2022-06-08 16:30 UTC, RonnyChiang commented on src/models/space/index.js
> +  async getZoneSpaces(zoneId, spaceType) {
fixed: controller 加入參數判斷 若有即[]concat; 若無即''
service層判斷若有即getSpacesByZoneAndSpaceTypes; 若無即getSpacesByZone

2022-06-08 16:30 UTC, RonnyChiang commented on src/controllers/field-controller.js
> +      const zoneList = await fieldService.getFieldZones(
fied

2022-06-08 16:31 UTC, RonnyChiang commented on src/models/zone.js
> +  async getFieldZones(fieldId, orientationId, levelId) {
fixed

2022-06-08 16:31 UTC, RonnyChiang commented on src/services/field-service.js
> +    this.logger.debug('got a fieldList', { fieldList });
fixed

2022-06-08 16:31 UTC, RonnyChiang commented on src/services/zone-service.js
> +    if (!spaces[0]) throw new GeneralError(getListErrorMap['zoneNotFound']);
fixed

2022-06-09 06:24 UTC, WendellLiu requested changes

2022-06-09 06:24 UTC, WendellLiu commented on src/controllers/field-controller.js
> +  getOrientationsByField: async (req, res, next) => {
nit: controller level naming 沒什麼問題耶，我覺得你可以改回來

2022-06-09 06:24 UTC, WendellLiu commented on src/controllers/zone-controller.js
> +      }
1. queryData 的命名太沒意義了，讓他有意義
2. const spaceType = queryData ? [].concat(queryData) : null

2022-06-09 06:24 UTC, WendellLiu commented on src/services/field-service.js
> +    if (!levelList[0]) throw new GeneralError(getListErrorMap['fieldNotFound']);
你改的結果還是蠻怪的
1. 你是想要認定是球場沒有level, orientation 資訊？如果是，為什麼還是field not found ，以及為什麼error message 可以用一樣的？
2. 你是想要認定是沒有該球場？但一來與你的判斷不符合，二來error message 也不符合

2022-06-09 06:24 UTC, WendellLiu commented on src/services/field-service.js
> +    // demo for local logger
不要照複製吧，這些明顯就是當初為了給你看（demo）的註解，接下來的log 怎麼會需要這個註解

2022-06-09 06:24 UTC, WendellLiu commented on src/services/zone-service.js
> +    }
你沒有抓到early return 的點
你為了避免if...else... 因為之前說prefer early return ，但事實上你這邊兩個if 顯然是有點奇怪，因為第一個之後第二個就必定成立，何需再一次 `if(spaceType)` ？

我認為你要不有個函數處理這件事，在那就可以更好做出early return ，要不就是這邊就if...else... ，而不是為了避免而寫出這種多餘的判斷

2022-06-09 06:24 UTC, WendellLiu commented on src/services/zone-service.js
> +    // demo for local logger
ditto

2022-06-09 07:36 UTC, RonnyChiang commented on src/controllers/zone-controller.js
> +      }
querySpaceType

2022-06-09 07:36 UTC, RonnyChiang commented on src/services/field-service.js
> +    // demo for local logger
fixed

2022-06-09 07:36 UTC, RonnyChiang commented on src/services/zone-service.js
> +    }
fixed by a function

2022-06-09 07:36 UTC, RonnyChiang commented on src/services/zone-service.js
> +    // demo for local logger
fixed

2022-06-09 08:27 UTC, WendellLiu commented on src/errors/getList-error.js
> +    message: '該區域無任何space資訊',
為何就出現一個英文？

2022-06-09 08:27 UTC, WendellLiu commented on src/services/zone-service.js
> +      return await spaceModel.getSpacesByZoneAndSpaceTypes(zoneId, spaceType);
看起來不是get a selector
不如就叫getSpaces

2022-06-09 08:27 UTC, WendellLiu commented on src/services/zone-service.js
> +    if (!spaces[0]) throw new GeneralError(getListErrorMap['spaceNotFound']);
何不直接看length? 也可以進一步使用isEmpty

2022-06-10 04:13 UTC, RonnyChiang commented on src/services/zone-service.js
> +      return await spaceModel.getSpacesByZoneAndSpaceTypes(zoneId, spaceType);
fixed

2022-06-10 04:13 UTC, RonnyChiang commented on src/errors/getList-error.js
> +    message: '該區域無任何space資訊',
fixed

2022-06-10 04:13 UTC, RonnyChiang commented on src/services/zone-service.js
> +    if (!spaces[0]) throw new GeneralError(getListErrorMap['spaceNotFound']);
fixed

2022-06-10 09:39 UTC, WendellLiu approved these changes

2022-06-10 15:26 UTC, merged