[CU-31u16ek] Cache field info
field-seating/field-seating-api pull request #43
Opened 2022-06-14 02:32 UTC by RonnyChiang

add cache for fields, levels, orientations, zones, and spaces

2022-06-14 02:32 UTC, WendellLiu commented
Task linked: [CU-31u16ek cache fields and its info](https://app.clickup.com/t/31u16ek)

2022-06-14 04:31 UTC, WendellLiu requested changes

2022-06-14 04:31 UTC, WendellLiu commented on src/cache/constants.js
> +const keyMap = {
expiredTime 以及version 抽出來這件事我認為是過度工程，既然已經用單一class 來表述一個情境下的caching ，我想共用的必要性是很低的。
而keyMap 我則是覺得稍微無謂了一點，但也一樣，因為也不會共用，也沒有改的可能，反之是在這邊共用只會增加其他人也用到一樣key 的可能。

2022-06-14 04:31 UTC, WendellLiu commented on src/cache/levels.js
> +class levelsCache extends CacheBase {
既然是get levels by fields 或許名稱可以更貼近一點。一個可能發生的問題就是如果另一個cache 背後是get levels 那這邊的命名看起來就尷尬了。

另外class 慣例是大寫

2022-06-14 04:31 UTC, WendellLiu commented on src/cache/orientations.js
> +class orientationsCache extends CacheBase {
ditto

2022-06-14 04:31 UTC, WendellLiu commented on src/cache/spaces.js
> +class zonesCache extends CacheBase {
ditto

2022-06-14 04:31 UTC, WendellLiu commented on src/cache/spaces.js
> +class zonesCache extends CacheBase {
而且為什麼是zonesCache?

2022-06-14 04:31 UTC, WendellLiu commented on src/cache/zones.js
> +class zonesCache extends CacheBase {
ditto

2022-06-14 12:20 UTC, RonnyChiang commented on src/cache/constants.js
> +const keyMap = {
已刪除

2022-06-14 12:20 UTC, RonnyChiang commented on src/cache/levels.js
> +class levelsCache extends CacheBase {
已修改  LevelsByFieldCache

2022-06-14 12:20 UTC, RonnyChiang commented on src/cache/orientations.js
> +class orientationsCache extends CacheBase {
ditto

2022-06-14 12:20 UTC, RonnyChiang commented on src/cache/spaces.js
> +class zonesCache extends CacheBase {
ditto 已修正

2022-06-14 12:20 UTC, RonnyChiang commented on src/cache/zones.js
> +class zonesCache extends CacheBase {
ditto

2022-06-14 15:39 UTC, RonnyChiang commented on src/cache/levels.js
> +    return 'levels';
fixed

2022-06-14 15:54 UTC, WendellLiu commented on src/cache/levels.js
> +class LevelsByFieldCache extends CacheBase {
我的錯，都沒注意到。file name 也要一起改

2022-06-15 02:14 UTC, RonnyChiang commented on src/cache/levels.js
> +class LevelsByFieldCache extends CacheBase {
fixed

2022-06-15 03:56 UTC, WendellLiu approved these changes

2022-06-15 04:27 UTC, merged