[CU-32b6cdv] Get photos
field-seating/field-seating-api pull request #47
Opened 2022-07-02 12:57 UTC by RonnyChiang

getPhotos API

2022-07-02 12:57 UTC, WendellLiu commented
Task linked: [CU-32b6cdv get photos](https://app.clickup.com/t/32b6cdv)

2022-07-02 15:16 UTC, RonnyChiang commented on src/config/config.development.js
> +  },
有用數淨額最小顯示值

2022-07-03 09:23 UTC, WendellLiu requested changes
另外，為什麼這些listing API 都沒有任何level 下的limit ，我以為我們談過這件事！？

2022-07-03 09:23 UTC, WendellLiu commented on src/services/photo-service.js
> +        }
1. no n^2; try to optimize it to 2n
2. 不需要那麼多次的merge ，看起來一次即可
3. 與其給出個flag 來表達是否有找到review ，否才給預設值；不如本來就先給預設值

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +  async getPhotosBySpace(id, sort, order) {
為什麼是space service ？

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +  async getOtherPhotosBySpace(spaceId, photoId) {
如上面說的，考慮重構這些方法們的介面

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +    let photosData = await Promise.all(
ditto; 為什麼需要promise

2022-07-03 09:23 UTC, WendellLiu commented on src/services/photo-service.test.js
> +    it('should return photoNotFound error', async () => {
ditto; 考慮適不適合有個錯誤

2022-07-03 09:23 UTC, WendellLiu commented on src/services/photo-service.test.js
> +    it('should return photosNotFound error', async () => {
ditto; 考慮適不適合有個錯誤

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +    if (isNil(space)) throw new GeneralError(getDataErrorMap['spaceNotFound']);
考慮錯誤

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +          photosData.splice(i, 1);
避免mutation

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +          photosData.splice(i, 1);
避免mutation

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +    );
參考上面的comment

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +      for (let i = photosData.length - 1; i >= 0; i--) {
filter

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +      for (let i = photosData.length - 1; i >= 0; i--) {
filter

2022-07-03 09:23 UTC, WendellLiu commented on src/config/config.development.js
> +    limit: -1,
1. 有什麼需求要不同環境不同數值？
2. 為什麼少了test environment

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +    );
其中某一段另外邏輯如此雷同，或許收斂成一個函數？

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +  async getPhotosBySpace(id, sort, order) {
讓可預測性高一點，sort, order 是否應該要有預設值。
對於使用者來說，如果沒有給sort, order ，他是否需要回到model 去看到底會是怎麼排序才行？

2022-07-03 09:23 UTC, WendellLiu commented on src/services/space-service/index.js
> +        if (photosData[i].netUsefulCount < uselessLimit.limit)
篩選這件事看起來你無論如何的會做，為什麼
1. 需要在if 內
2. 可以從model level ，甚至sql level 做掉嗎？

2022-07-03 13:00 UTC, WendellLiu commented on src/services/photo-service.js
> +        }
const photosWithReviewCountMap = indexOf(prop('photoId'))(photosWithReviewCount)

2022-07-03 13:11 UTC, WendellLiu commented on src/services/space-service/index.js
> +          photosData.splice(i, 1);
slice

2022-07-08 06:31 UTC, RonnyChiang commented on src/services/photo-service.js
> +    if (!photo) throw new GeneralError(getPhotoErrorMap['photoNotFound']);
fixed

2022-07-08 06:32 UTC, RonnyChiang commented on src/services/photo-service.js
> +    this.logger.debug('got a photo', { photo });
fixed

2022-07-08 06:32 UTC, RonnyChiang commented on src/services/space-service/index.js
> +module.exports = SpaceService;
ok

2022-07-08 06:32 UTC, RonnyChiang commented on src/controllers/photo-controller.js
> +      photos.unshift(startPhoto);
fixed to one service

2022-07-08 06:32 UTC, RonnyChiang commented on src/services/photo-service.js
> +      throw new GeneralError(getPhotoErrorMap['photosNotFound']);
fixed

2022-07-08 06:32 UTC, RonnyChiang commented on src/services/photo-service.js
> +    const photosWithReviewCount = await photoModel.getPhotosReviewCount();
fixed

2022-07-08 06:32 UTC, RonnyChiang commented on src/controllers/space-controller.js
> +const SpaceService = require('../services/space-service/index');
fixed

2022-07-08 06:32 UTC, RonnyChiang commented on src/models/photo.js
> +    const photos = await prisma.photos.findMany({
fixed

2022-07-08 06:33 UTC, RonnyChiang commented on src/models/review/index.js
> +  constructor() {}
fixed

2022-07-08 06:33 UTC, RonnyChiang commented on src/models/review/index.js
> +    WHERE Reviews.photoId  = ${photoId}
prisma so good

2022-07-08 06:33 UTC, RonnyChiang commented on src/services/photo-service.js
> +    }
fixed

2022-07-08 06:33 UTC, RonnyChiang commented on src/services/photo-service.js
> +      netUsefulCount: reviewCount[0].netUsefulCount,
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/photo-service.js
> +    let photosData = await Promise.all(
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/photo-service.js
> +        }
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/space-service/index.js
> +  async getOtherPhotosBySpace(spaceId, photoId) {
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/space-service/index.js
> +    let photosData = await Promise.all(
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/photo-service.test.js
> +    it('should return photoNotFound error', async () => {
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/photo-service.test.js
> +    it('should return photosNotFound error', async () => {
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/space-service/index.js
> +    if (isNil(space)) throw new GeneralError(getDataErrorMap['spaceNotFound']);
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/space-service/index.js
> +          photosData.splice(i, 1);
fixed

2022-07-08 06:35 UTC, RonnyChiang commented on src/services/space-service/index.js
> +          photosData.splice(i, 1);
fixed

2022-07-08 06:36 UTC, RonnyChiang commented on src/services/space-service/index.js
> +    );
fixed

2022-07-08 06:36 UTC, RonnyChiang commented on src/services/space-service/index.js
> +      for (let i = photosData.length - 1; i >= 0; i--) {
fixed

2022-07-08 06:36 UTC, RonnyChiang commented on src/services/space-service/index.js
> +      for (let i = photosData.length - 1; i >= 0; i--) {
fixed

2022-07-08 06:36 UTC, RonnyChiang commented on src/config/config.development.js
> +    limit: -1,
fixed and added

2022-07-08 06:36 UTC, RonnyChiang commented on src/services/space-service/index.js
> +        if (photosData[i].netUsefulCount < uselessLimit.limit)
fixed

2022-07-08 09:17 UTC, WendellLiu requested changes

2022-07-08 09:17 UTC, WendellLiu commented on src/models/photo.js
> +    } else {
看起來不需要else

2022-07-08 09:17 UTC, WendellLiu commented on src/models/photo.js
> +    cursorId
請好好安排你的參數，不管是順序還是形式、預設值。不要將有預設值的參數安插在中間。

2022-07-08 09:17 UTC, WendellLiu commented on src/models/photo.js
> +    } else {
no needed else for early return pattern

2022-07-08 09:17 UTC, WendellLiu commented on src/models/photo.js
> +    } else {
ditto

2022-07-08 09:17 UTC, WendellLiu commented on src/models/photo.js
> +  async getPhotosReviewCount(photosId) {
photoIds

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +const { paginationLimit } = require('../constants/photo-constant');
他有什麼需要被分享的理由嗎？

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +  async getPhotos(startPhotoId, limit = paginationLimit, cursorId) {
重新安排你的參數

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +    let photos = [];
看起來photos 不是陣列

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +    // if no startPhoto query
startPhotoid

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +      const photoModel = new PhotoModel();
什麼理由需要再重新建立一個instance ?

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +    return result;
從頭到尾的return 都是不同型別，請確定你回傳值的型別是什麼

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +    let photosData = photos.data.map((photo) => {
為什麼是let ?

2022-07-08 09:17 UTC, WendellLiu commented on src/services/photo-service.js
> +      const dataset = renderDataset(sizeMap.seatPhoto)({
renderDataset(sizeMap.seatPhoto) 可以往外放吧

2022-07-08 09:17 UTC, WendellLiu commented on src/services/space-service/index.js
> +    return result;
問題都與photo service 中的方法一樣

2022-07-08 09:19 UTC, WendellLiu commented on src/services/photo-service.js
> +    return result;
整個流程能夠整理一下嗎？
1. 是不是能先做完validation
2. 比較複雜的邏輯是不是能抽出去作為一個helper

2022-07-08 09:22 UTC, WendellLiu commented on src/controllers/photo-controller.js
> +      const photos = await photoService.getPhotos(
這裡不是photos 了吧，型別要顧好

2022-07-08 09:28 UTC, WendellLiu commented on src/controllers/photo-controller.js
> +      res.status(200).json(resSuccess(photos));
另外有一件事，不是問題，就單純是個分享。我這邊也漏了，陰錯陽差你改成有分頁才沒讓這個問題發生：
一開始訂定API 時就應該要涵蓋pagination 的概念進去，至少不會是回傳一個陣列，而是事先就以object 包住陣列的部分，否則當實質加入分頁資訊後，會是API Breaking

2022-07-08 10:09 UTC, RonnyChiang commented on src/services/photo-service.js
> +const { paginationLimit } = require('../constants/photo-constant');
修正為pagination-constant , paginationLimitMap 可存放各種類型的pagination limit photos: 5 record:10...

2022-07-09 06:50 UTC, RonnyChiang commented on src/models/photo.js
> +    } else {
fixed

2022-07-09 06:50 UTC, RonnyChiang commented on src/models/photo.js
> +    cursorId
fixed

2022-07-09 06:50 UTC, RonnyChiang commented on src/models/photo.js
> +    } else {
fixed

2022-07-09 06:50 UTC, RonnyChiang commented on src/models/photo.js
> +    } else {
fixed

2022-07-09 06:53 UTC, RonnyChiang commented on src/models/photo.js
> +  async getPhotosReviewCount(photosId) {
fixed

2022-07-09 06:54 UTC, RonnyChiang commented on src/services/photo-service.js
> +  async getPhotos(startPhotoId, limit = paginationLimit, cursorId) {
fixed paginationOption {}

2022-07-09 06:55 UTC, RonnyChiang commented on src/services/photo-service.js
> +    let photos = [];
fixed to null

2022-07-09 06:56 UTC, RonnyChiang commented on src/services/photo-service.js
> +    // if no startPhoto query
fixed

2022-07-09 06:57 UTC, RonnyChiang commented on src/services/photo-service.js
> +      const photoModel = new PhotoModel();
deleted

2022-07-09 06:57 UTC, RonnyChiang commented on src/services/photo-service.js
> +    return result;
fixed {}

2022-07-09 06:58 UTC, RonnyChiang commented on src/services/photo-service.js
> +    let photosData = photos.data.map((photo) => {
fixed

2022-07-09 06:58 UTC, RonnyChiang commented on src/services/photo-service.js
> +      const dataset = renderDataset(sizeMap.seatPhoto)({
fixed to combine helper

2022-07-09 06:58 UTC, RonnyChiang commented on src/services/space-service/index.js
> +    return result;
fixed

2022-07-09 07:02 UTC, RonnyChiang commented on src/services/photo-service.js
> +    return result;
[Flow Chart](https://app.clickup.com/25699357/v/dc/rg90x-285/rg90x-800)
getPhotos 將combine 抽出至 combine-hepler
getPhotosBySpace 將combine 抽出至 combine-hepler, sort抽取至sort-helper, spaceCheck 拉到controller

2022-07-09 07:02 UTC, RonnyChiang commented on src/controllers/photo-controller.js
> +      const photos = await photoService.getPhotos(
fixed to result

2022-07-09 07:02 UTC, RonnyChiang commented on src/controllers/photo-controller.js
> +      res.status(200).json(resSuccess(photos));
got it!

2022-07-11 09:43 UTC, WendellLiu commented on src/controllers/space-controller.js
> +      let result = null;
為什麼需要先定義result ?

2022-07-11 09:43 UTC, WendellLiu commented on src/models/photo.js
> +  async getPhotosBySpace(spaceId, order = 'desc', { limit } = {}) {
何不把「次要」的order, limit, cursor 都擺在一起？

2022-07-11 09:43 UTC, WendellLiu commented on src/models/photo.js
> +  async getOtherPhotosBySpace(spaceId, photoId, { limit } = {}) {
ditto

2022-07-11 09:43 UTC, WendellLiu commented on src/services/helpers/combine-helper.js
> +module.exports = { combine };
命名、參數都不是很協調，最後都是回歸到你對於函數scope 的認知
1. 首先combine ，不是很容易理解你這是在combine 什麼
2. 再來，你想要抽象的是什麼事？有些東西是固定的（e.g. sizeMap, bucketMap），而有些又是變動的（e.g. dataList, mapData）。然後相對照的函數名稱又是這麼廣埸，所以這個函數的scope 到底是什麼呢？

2022-07-11 09:43 UTC, WendellLiu commented on src/services/helpers/sort-helper.js
> +};
相對於combine-helper 而言，這個就相對定義的很好，既然是sort ，就是把資料、與order 策略都作為可變動的項目。
唯一，為什麼作為 service/helpers/sort-helper 可以確定只用「netUsefulCount」做排序？

2022-07-11 09:43 UTC, WendellLiu commented on src/services/photo-service.js
> +      photos = combinedPhotos;
而且看不太懂為什麼這邊是combinedPhotos ？看起來你要的combine 在底下？

2022-07-11 12:53 UTC, RonnyChiang commented on src/services/photo-service.js
> +      photos = combinedPhotos;
otherPhotos.data.slice(0, -1);
      [startPhoto].concat(otherPhotos.data);
      photos = otherPhotos;

2022-07-11 13:17 UTC, RonnyChiang commented on src/services/helpers/sort-helper.js
> +};
function sortHelper(data, order, prop) {
  if (order === orderMap.desc) return data.sort((a, b) => b[prop] - a[prop]);
  if (order === orderMap.asc) return data.sort((a, b) => a[prop] - b[prop]);
}

2022-07-11 13:18 UTC, RonnyChiang commented on src/models/photo.js
> +  async getOtherPhotosBySpace(spaceId, photoId, { limit } = {}) {
not need

2022-07-11 15:12 UTC, RonnyChiang commented on src/controllers/space-controller.js
> +      let result = null;
![Uploading 截圖 2022-07-11 下午11.11.43.png…]()

2022-07-11 15:15 UTC, RonnyChiang commented on src/controllers/space-controller.js
> +      let result = null;
if (isNil(space)) {
        res.status(200).json(resSuccess(space));
        next();
      } else {
        const result = await spaceService.getPhotosBySpace(
          id,
          paginationOption
        );
        res.status(200).json(resSuccess(result));
      }

2022-07-11 15:15 UTC, RonnyChiang commented on src/models/photo.js
> +  async getPhotosBySpace(spaceId, order = 'desc', { limit } = {}) {
fixed

2022-07-11 16:34 UTC, RonnyChiang commented on src/services/helpers/combine-helper.js
> +module.exports = { combine };
fixed

2022-07-12 05:58 UTC, WendellLiu commented on src/services/helpers/render-photo-response-helper.js
> +module.exports = { renderPhotoResponse };
你打算會有其他helper?

2022-07-12 05:58 UTC, WendellLiu commented on src/services/helpers/render-photo-response-helper.js
> +function renderPhotoResponse(dataList, mapData, size, bucket) {
sizeMap, bucketMap or sizeConfig, bucketConfig

2022-07-12 05:58 UTC, WendellLiu commented on src/services/helpers/sort-helper.js
>  module.exports = {
一樣，你會有其他helper?
如果有，那你在sort-helper 裡面的sortHelper 是不是應該改名，或是如果沒有，是不是直接export

2022-07-12 05:58 UTC, WendellLiu commented on src/services/space-service/index.js
> +    photosData = sortHelper(photosData, paginationOption.order, countMap.net);
nit: 我覺得如果是prop ，沒什麼必要給常數。除非你所有get value by property 都會用常數，例如你上面的`photo.netUsefulCount` 也應該用常數

2022-07-12 08:24 UTC, WendellLiu approved these changes

2022-07-12 08:37 UTC, merged