fix: change order
field-seating/field-seating-api pull request #62
Opened 2022-08-02 08:04 UTC by RonnyChiang

generate token --> send verify email --> flush db token

2022-08-02 09:43 UTC, WendellLiu requested changes
為這個fix 增加一個test case

2022-08-03 08:26 UTC, WendellLiu commented on src/config/config.development.js
> +      limit: 5, // for dev
no need

2022-08-03 08:30 UTC, WendellLiu commented on src/services/user-service/user-service.test.js
> +        expect(e.code).toBe(sendEmailErrorMap.exceedLimitError.code);
所以userService.resendVerifyEmail 沒發生錯誤，這個testcase 就會過？

2022-08-03 10:04 UTC, WendellLiu commented on src/services/user-service/index.js
> +    return newToken;
early return 空行

2022-08-03 10:07 UTC, WendellLiu commented on src/services/user-service/user-service.test.js
> +      const UserService = require('.');
為什麼需要import 一次?

2022-08-03 18:30 UTC, RonnyChiang commented on src/config/config.development.js
> +      limit: 5, // for dev
fixed

2022-08-03 18:30 UTC, RonnyChiang commented on src/services/user-service/user-service.test.js
> +        expect(e.code).toBe(sendEmailErrorMap.exceedLimitError.code);
fixed finally

2022-08-03 18:30 UTC, RonnyChiang commented on src/services/user-service/index.js
> +    return newToken;
fixed

2022-08-03 18:30 UTC, RonnyChiang commented on src/services/user-service/user-service.test.js
> +      const UserService = require('.');
fixed

2022-08-04 02:16 UTC, WendellLiu approved these changes

2022-08-04 04:31 UTC, merged