Post report
field-seating/field-seating-api pull request #69
Opened 2022-08-19 06:34 UTC by RonnyChiang

2022-08-19 06:36 UTC, WendellLiu commented
Task linked: [CU-3b97kgb POST /photos/:photo_id/report](https://app.clickup.com/t/3b97kgb)

2022-08-22 08:35 UTC, WendellLiu requested changes

2022-08-22 08:35 UTC, WendellLiu commented on src/models/report/index.js
> +  async getReport(photoId, userId) {
get reports by photo id and user id

2022-08-22 08:35 UTC, WendellLiu commented on src/services/report-service/index.js
> +    // set rate limit use userId or ip by auth or not
不加入照片？

2022-08-22 08:35 UTC, WendellLiu commented on src/services/report-service/index.js
> +    const photoCheck = await photoModel.getPhoto(parseInt(photoId));
hasPhoto

2022-08-22 08:35 UTC, WendellLiu commented on src/services/report-service/index.js
> +        throw new GeneralError(reportErrorMap['duplicateError']);
應該沒有說好會有錯誤吧？我想到的是，如果不能讓使用者先知道他有沒有回報過，卻在這邊回給他錯誤，不是很好的體驗

2022-08-22 13:52 UTC, RonnyChiang commented on src/services/report-service/index.js
> +    const photoCheck = await photoModel.getPhoto(parseInt(photoId));
ok

2022-08-22 13:53 UTC, RonnyChiang commented on src/services/report-service/index.js
> +        throw new GeneralError(reportErrorMap['duplicateError']);
return report( same with postReport)

2022-08-23 08:45 UTC, WendellLiu requested changes

2022-08-23 08:45 UTC, WendellLiu commented on src/services/report-service/index.js
> +      if (!isEmpty(report)) return report;
應該能不要兩層的if

2022-08-23 14:06 UTC, WendellLiu commented on src/services/report-service/index.js
> +    const report = userId
reports

2022-08-23 15:34 UTC, WendellLiu approved these changes

2022-08-24 03:06 UTC, merged