[CU-3cq0h2w] feat: put Report
field-seating/field-seating-api pull request #72
Opened 2022-08-31 09:25 UTC by RonnyChiang

2022-08-31 09:25 UTC, WendellLiu commented
Task linked: [CU-3cq0h2w PUT /admin/photos/:id/resolve](https://app.clickup.com/t/3cq0h2w)

2022-08-31 09:36 UTC, RonnyChiang commented
[API doc](https://app.clickup.com/25699357/v/dc/rg90x-245/rg90x-265?block=block-db380d9b-4c52-429c-b944-5d6eb9774e2b)

2022-09-02 06:04 UTC, WendellLiu requested changes

2022-09-02 06:04 UTC, WendellLiu commented on src/services/report-service/report-service.test.js
> +  describe('with not exist reportId', () => {
with no or without

2022-09-02 06:04 UTC, WendellLiu commented on src/services/report-service/index.js
> +    if (status === 'deleted') {
status map

2022-09-03 15:26 UTC, RonnyChiang commented on src/models/report/index.js
> +  async putReportsByPhotoId(photoId, status) {
fixed

2022-09-03 15:26 UTC, RonnyChiang commented on src/services/photo-service/index.js
> +      if (isEmpty(startPhoto))
修正

2022-09-03 15:26 UTC, RonnyChiang commented on src/services/report-service/index.js
> +    const hasReport = await reportModel.getReportByReportId(parseInt(reportId));
fixed

2022-09-03 15:26 UTC, RonnyChiang commented on src/services/report-service/report-service.test.js
> +  describe('with not exist reportId', () => {
fixed

2022-09-03 15:26 UTC, RonnyChiang commented on src/services/report-service/index.js
> +    if (status === 'deleted') {
fixed

2022-09-05 08:55 UTC, WendellLiu reviewed
主要邏輯沒問題，幾個小地方

2022-09-05 08:55 UTC, WendellLiu commented on src/models/photo/index.js
> +        deletedAt: new Date(Date.now()),
這跟 new Date() 有什麼不同嗎？

2022-09-05 08:55 UTC, WendellLiu commented on src/services/report-service/index.js
> +    if (report && report.status !== 'pending')
status map

2022-09-06 07:55 UTC, RonnyChiang commented on src/models/photo/index.js
> +        deletedAt: new Date(Date.now()),
沒有，已修正

2022-09-06 07:55 UTC, RonnyChiang commented on src/services/report-service/index.js
> +    if (report && report.status !== 'pending')
fixed

2022-09-06 07:56 UTC, WendellLiu approved these changes

2022-09-06 07:56 UTC, merged