Fix get report
field-seating/field-seating-api pull request #75
Opened 2022-10-19 08:06 UTC by RonnyChiang

* fix: getReportPhotos controller & service & model

* feat: getReportsPhotos test

2022-10-19 08:07 UTC, WendellLiu commented
Task linked: [CU-3kj0mhy fix get report be filter by status](https://app.clickup.com/t/3kj0mhy)

2022-10-19 08:21 UTC, WendellLiu requested changes

2022-10-19 08:21 UTC, WendellLiu commented on src/services/report-service/index.js
> +      !Object.prototype.hasOwnProperty.call(statusMap, paginationOption.filter) // https://eslint.org/docs/latest/rules/no-prototype-builtins
為什麼要這麼複雜的方式來判斷有沒有在map 中？

2022-10-19 08:21 UTC, WendellLiu commented on src/services/report-service/index.js
> +      throw new GeneralError(reportErrorMap['wrongReportStatusType']);
我覺得就性質而言，錯誤不是一個好主意

2022-10-19 09:09 UTC, RonnyChiang commented on src/services/report-service/index.js
> +      !Object.prototype.hasOwnProperty.call(statusMap, paginationOption.filter) // https://eslint.org/docs/latest/rules/no-prototype-builtins
!(paginationOption.filter in statusMap) ?

2022-10-20 07:00 UTC, WendellLiu approved these changes

2022-10-20 07:07 UTC, merged