[CU-3qnqp76] fix: something wrong
field-seating/field-seating-api pull request #77
Opened 2022-11-01 16:13 UTC by RonnyChiang

* add update to admin srcipt

2022-11-01 16:13 UTC, WendellLiu commented
Task linked: [CU-3qnqp76 updateToAdmin script](https://app.clickup.com/t/3qnqp76)

2022-11-02 00:20 UTC, WendellLiu requested changes

2022-11-02 00:20 UTC, WendellLiu commented on data/utils/update-to-admin.js
> +async function updateToAdmin(userId) {
1. 因為model 已經有update one user to admin 的方法，也不要求提供更新多位的方法了；不過util 的介面可以改成接受多個user id
2. 你的 `logger.info(`user:${userId} not found`)` 難道不會無論有沒有user 都跑到？
可以考慮針對 nil user 作early return 比較直覺

2022-11-02 03:25 UTC, RonnyChiang commented on data/utils/update-to-admin.js
> +async function updateToAdmin(userId) {
1. fix by [1, 2] 
2. early return

2022-11-03 05:26 UTC, WendellLiu commented on data/utils/update-to-admin.js
> +  });
我不確定這樣能不能讓updateToAdmin wait for all operation ，你可以測試看看。但我覺得這個情境用Promise all 來做會很合理

2022-11-08 07:40 UTC, WendellLiu approved these changes

2022-11-08 08:32 UTC, merged